-- Seed craft_types with common crafts
insert into craft_types (name, is_custom) values
  ('Knitting', false),
  ('Crochet', false),
  ('Needlepoint', false),
  ('Sewing', false),
  ('Resin', false),
  ('Embroidery', false),
  ('Macramé', false),
  ('Weaving', false),
  ('Quilting', false),
  ('Cross Stitch', false),
  ('Felting', false),
  ('Candle Making', false),
  ('Jewelry Making', false),
  ('Scrapbooking', false),
  ('Paper Crafts', false),
  ('Pottery', false),
  ('Ceramics', false),
  ('Woodworking', false),
  ('Leather Working', false),
  ('Glass Blowing', false),
  ('Stained Glass', false),
  ('Calligraphy', false),
  ('Latch Hook', false),
  ('Rug Hooking', false),
  ('Tatting', false),
  ('Beadwork', false),
  ('Mosaic', false),
  ('Soap Making', false),
  ('Dyeing', false),
  ('Spinning', false),
  ('Polymer Clay', false)
on conflict (name) do nothing;
